// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('10. desactivar varios', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('10. desactivar varios', async function() {
    await driver.get("https://vayo-solutions.netlify.app/")
    await driver.findElement(By.linkText("Ingresar")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("admin@vayo.cl")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Admin2026!")
    await driver.findElement(By.css(".btn")).click()
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.manage().window().setRect(1360, 658)
    await driver.findElement(By.linkText("Productos")).click()
    await driver.findElement(By.linkText("Categorías")).click()
    {
      const element = await driver.findElement(By.linkText("Categorías"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css("tr:nth-child(11) .btn--ghost-danger")).click()
    await driver.findElement(By.css(".btn--danger")).click()
    await driver.findElement(By.linkText("Clientes")).click()
    await driver.findElement(By.css("tr:nth-child(45) .action-menu > .btn")).click()
    await driver.findElement(By.css("tr:nth-child(42) .action-menu > .btn")).click()
    await driver.findElement(By.css(".action-menu__danger")).click()
    await driver.findElement(By.css(".btn--danger")).click()
    await driver.findElement(By.linkText("Reportes")).click()
    await driver.findElement(By.linkText("Usuarios")).click()
    {
      const element = await driver.findElement(By.linkText("Usuarios"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("tr:nth-child(3) .btn--ghost-danger")).click()
    await driver.findElement(By.css(".btn--danger")).click()
    await driver.findElement(By.linkText("Proveedores")).click()
    {
      const element = await driver.findElement(By.linkText("Proveedores"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("tr:nth-child(6) .btn--ghost-danger")).click()
    await driver.findElement(By.css(".btn--danger")).click()
    await driver.findElement(By.linkText("Reseñas")).click()
    {
      const element = await driver.findElement(By.linkText("Configuración"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Configuración")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    {
      const element = await driver.findElement(By.linkText("Reseñas"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".btn--ghost")).click()
  })
})
