// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('11. reactivar', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('11. reactivar', async function() {
    await driver.get("https://vayo-solutions.netlify.app/")
    await driver.manage().window().setRect(1051, 797)
    await driver.findElement(By.linkText("Ingresar")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("admin@vayo.cl")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Admin2026!")
    await driver.findElement(By.css(".btn")).click()
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.linkText("Productos")).click()
    await driver.findElement(By.css("tr:nth-child(2) .btn--ghost-danger")).click()
    await driver.findElement(By.css(".btn--danger")).click()
    await driver.findElement(By.css(".row--inactive:nth-child(2) .btn:nth-child(2)")).click()
    await driver.findElement(By.linkText("Categorías")).click()
    await driver.findElement(By.css(".row--inactive:nth-child(11) .btn:nth-child(2)")).click()
    await driver.findElement(By.css(".btn--outline:nth-child(2)")).click()
    await driver.executeScript("window.scrollTo(0,0)")
    await driver.findElement(By.linkText("Cotizaciones")).click()
    await driver.findElement(By.linkText("Ventas")).click()
    await driver.findElement(By.linkText("Clientes")).click()
    await driver.findElement(By.css(".row--inactive:nth-child(6) .action-menu > .btn")).click()
    await driver.findElement(By.css("li:nth-child(3) > button")).click()
    await driver.findElement(By.css(".row--inactive:nth-child(39) .action-menu > .btn")).click()
    await driver.findElement(By.css("li:nth-child(3) > button")).click()
    await driver.findElement(By.linkText("Usuarios")).click()
    {
      const element = await driver.findElement(By.linkText("Usuarios"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("tr:nth-child(3) .btn--ghost-danger")).click()
    await driver.findElement(By.css(".btn--danger")).click()
    await driver.findElement(By.css(".btn--outline:nth-child(2)")).click()
    await driver.findElement(By.linkText("Proveedores")).click()
    await driver.findElement(By.css(".btn--outline:nth-child(2)")).click()
    await driver.findElement(By.css(".btn--outline:nth-child(2)")).click()
    {
      const element = await driver.findElement(By.css(".btn--outline:nth-child(2)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.close()
  })
})
