// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('1. Login y Logout', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    await driver.manage().setTimeouts({ implicit: 10000 })
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('1. Login y Logout', async function() {
    await driver.get("https://vayo-solutions.netlify.app/")
    await driver.manage().window().setRect(1024, 536)
    await driver.findElement(By.linkText("Ingresar")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("admin@vayo.cl")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Admin2026!")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.css(".admin-shell__content")).click()
    await driver.findElement(By.css(".btn--ghost")).click()
    await driver.close()
  })
})
