// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('2. Crear producto', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('2. Crear producto', async function() {
    await driver.get("https://vayo-solutions.netlify.app/")
    await driver.manage().window().setRect(1024, 536)
    await driver.findElement(By.linkText("Ingresar")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("admin@vayo.cl")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Admin2026!")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.linkText("Productos")).click()
    await driver.findElement(By.css(".block-head")).click()
    await driver.findElement(By.css(".btn--primary")).click()
    await driver.findElement(By.css(".btn--primary")).click()
    await driver.findElement(By.id("pr-cat")).click()
    {
      const dropdown = await driver.findElement(By.id("pr-cat"))
      await dropdown.findElement(By.xpath("//option[. = 'Manual Enciclopedia Collection']")).click()
    }
    await driver.findElement(By.id("pr-name")).click()
    await driver.findElement(By.id("pr-name")).sendKeys("Manual de Test")
    await driver.findElement(By.id("pr-sku")).click()
    await driver.findElement(By.id("pr-sku")).sendKeys("Demo-Libro-002")
    await driver.findElement(By.id("pr-brand")).click()
    await driver.findElement(By.id("pr-brand")).sendKeys("Test")
    await driver.findElement(By.id("pr-model")).click()
    await driver.findElement(By.id("pr-model")).sendKeys("TF-30")
    await driver.findElement(By.id("pr-avail")).click()
    {
      const dropdown = await driver.findElement(By.id("pr-avail"))
      await dropdown.findElement(By.xpath("//option[. = 'Sin stock']")).click()
    }
    await driver.findElement(By.id("pr-desc")).click()
    await driver.findElement(By.id("pr-desc")).sendKeys("Test")
    await driver.findElement(By.css(".btn--sm:nth-child(2)")).click()
    await driver.findElement(By.css(".btn--ghost")).click()
  })
})
