// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('4. Crear Cliente', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('4. Crear Cliente', async function() {
    await driver.get("https://vayo-solutions.netlify.app/")
    await driver.findElement(By.linkText("Ingresar")).click()
    await driver.findElement(By.css(".login-card")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("admin@vayo.cl")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Admin2026!")
    await driver.findElement(By.css(".btn")).click()
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.manage().window().setRect(1024, 536)
    {
      const element = await driver.findElement(By.linkText("Clientes"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.linkText("Clientes")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".btn--primary")).click()
    await driver.findElement(By.id("c-name")).click()
    await driver.findElement(By.id("c-name")).sendKeys("Test")
    await driver.findElement(By.id("c-company")).click()
    await driver.findElement(By.id("c-company")).sendKeys("Prueba")
    await driver.findElement(By.id("c-rut")).click()
    await driver.findElement(By.id("c-rut")).sendKeys("00.000.000-0")
    await driver.findElement(By.id("c-email")).click()
    await driver.findElement(By.id("c-email")).sendKeys("test@cliente.cl")
    await driver.findElement(By.id("c-phone")).click()
    await driver.findElement(By.id("c-phone")).click()
    await driver.findElement(By.id("c-phone")).click()
    await driver.findElement(By.id("c-phone")).sendKeys("00000000")
    await driver.findElement(By.css(".form-grid:nth-child(3) > .form-field:nth-child(2) > .form-label")).click()
    await driver.findElement(By.id("c-address")).click()
    await driver.findElement(By.id("c-address")).sendKeys("calle test")
    await driver.findElement(By.id("c-notes")).click()
    await driver.findElement(By.id("c-notes")).sendKeys("test")
    await driver.findElement(By.css("div:nth-child(3) > .btn--primary")).click()
    await driver.findElement(By.css(".btn--ghost")).click()
    {
      const element = await driver.findElement(By.linkText("Crear cuenta"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
  })
})
