// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('5. Crear Usuario interno', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('5. Crear Usuario interno', async function() {
    await driver.get("https://vayo-solutions.netlify.app/admin")
    await driver.manage().window().setRect(1024, 536)
    await driver.findElement(By.linkText("Usuarios")).click()
    {
      const element = await driver.findElement(By.linkText("Usuarios"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".btn--primary")).click()
    await driver.findElement(By.id("usr-name")).click()
    await driver.findElement(By.id("usr-name")).sendKeys("Testeo")
    await driver.findElement(By.id("usr-email")).click()
    await driver.findElement(By.id("usr-email")).sendKeys("testeo@cotizador.cl")
    await driver.findElement(By.id("usr-pass")).click()
    await driver.findElement(By.id("usr-pass")).click()
    await driver.findElement(By.id("usr-pass")).click()
    {
      const element = await driver.findElement(By.id("usr-pass"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("usr-pass")).click()
    await driver.findElement(By.id("usr-pass")).sendKeys("tesst")
    await driver.findElement(By.id("usr-pos")).click()
    await driver.findElement(By.id("usr-pos")).sendKeys("testeer")
    await driver.findElement(By.id("usr-phone")).click()
    await driver.findElement(By.id("usr-phone")).sendKeys("00000000")
    await driver.findElement(By.id("usr-pass")).click()
    await driver.findElement(By.id("usr-pass")).sendKeys("12345678")
    await driver.findElement(By.css(".btn--sm:nth-child(2)")).click()
  })
})
