// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('6. Crear proveedor', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('6. Crear proveedor', async function() {
    await driver.get("https://vayo-solutions.netlify.app/admin")
    await driver.manage().window().setRect(1024, 536)
    {
      const element = await driver.findElement(By.linkText("Categorías"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.linkText("Proveedores")).click()
    {
      const element = await driver.findElement(By.linkText("Proveedores"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".btn--primary")).click()
    await driver.findElement(By.id("sup-name")).click()
    await driver.findElement(By.id("sup-name")).sendKeys("Tester2")
    await driver.findElement(By.id("sup-loc")).click()
    await driver.findElement(By.id("sup-loc")).sendKeys("Santiago")
    await driver.findElement(By.id("sup-phone")).click()
    await driver.findElement(By.id("sup-phone")).sendKeys("00000000")
    await driver.findElement(By.id("sup-email")).click()
    await driver.findElement(By.id("sup-email")).sendKeys("tester2@demo.cl")
    await driver.findElement(By.id("sup-notes")).click()
    await driver.findElement(By.id("sup-notes")).sendKeys("test")
    await driver.findElement(By.css(".btn--sm:nth-child(2)")).click()
  })
})
