// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('9. Desactivar producto', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('9. Desactivar producto', async function() {
    await driver.get("https://vayo-solutions.netlify.app/")
    await driver.findElement(By.linkText("Ingresar")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("admin@vayo.cl")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Admin2026!")
    await driver.findElement(By.css(".btn")).click()
    await driver.manage().window().setRect(1024, 536)
    await driver.findElement(By.linkText("Productos")).click()
    {
      const element = await driver.findElement(By.linkText("Productos"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".btn--primary")).click()
    {
      const element = await driver.findElement(By.css(".btn--primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("pr-cat")).click()
    {
      const dropdown = await driver.findElement(By.id("pr-cat"))
      await dropdown.findElement(By.xpath("//option[. = 'Test']")).click()
    }
    await driver.findElement(By.id("pr-name")).click()
    await driver.findElement(By.id("pr-name")).sendKeys("ertwER")
    await driver.findElement(By.id("pr-sku")).click()
    await driver.findElement(By.id("pr-sku")).sendKeys("qwraRWS")
    await driver.findElement(By.id("pr-brand")).click()
    await driver.findElement(By.id("pr-brand")).sendKeys("qwrqwae")
    await driver.findElement(By.id("pr-model")).click()
    await driver.findElement(By.id("pr-model")).sendKeys("QwEqrw")
    await driver.findElement(By.id("pr-stock")).click()
    await driver.findElement(By.id("pr-avail")).click()
    await driver.findElement(By.id("pr-avail")).click()
    {
      const dropdown = await driver.findElement(By.id("pr-avail"))
      await dropdown.findElement(By.xpath("//option[. = 'Sin stock']")).click()
    }
    await driver.findElement(By.id("pr-desc")).click()
    await driver.findElement(By.id("pr-desc")).click()
    {
      const element = await driver.findElement(By.id("pr-desc"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.id("pr-desc")).sendKeys("RASfdqatgfV")
    await driver.findElement(By.css(".btn--sm:nth-child(2)")).click()
    await driver.findElement(By.css("tr:nth-child(1) > .td--name")).click()
    await driver.findElement(By.css("tbody")).click()
    await driver.findElement(By.css("tr:nth-child(1) .btn--ghost-danger")).click()
    await driver.findElement(By.css(".btn--danger")).click()
    await driver.findElement(By.css(".btn--ghost")).click()
    await driver.close()
  })
})
