// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('1, Login falllido', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('1, Login falllido', async function() {
    await driver.get("https://vayo-solutions.netlify.app/")
    await driver.manage().window().setRect(1024, 536)
    await driver.findElement(By.linkText("Ingresar")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("azsdasd")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("EWASFDRRASF")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("ASFFAS@skfjlsknfoi")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.css("path:nth-child(2)")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("maria@vayo.cl")
    await driver.findElement(By.css("path")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.css(".login-card")).click()
    {
      const element = await driver.findElement(By.css(".login-card"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
  })
})
