// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('2. registro fallido', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('2. registro fallido', async function() {
    await driver.get("https://vayo-solutions.netlify.app/admin")
    await driver.manage().window().setRect(1051, 797)
    await driver.findElement(By.css(".btn--ghost")).click()
    await driver.findElement(By.linkText("Crear cuenta")).click()
    await driver.findElement(By.css(".form-group:nth-child(1)")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("2213")
    await driver.findElement(By.id("rut")).click()
    await driver.findElement(By.id("rut")).sendKeys("12-3")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("123")
    {
      const element = await driver.findElement(By.css(".form-group:nth-child(4)"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    {
      const element = await driver.findElement(By.id("phone"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("123")
    await driver.findElement(By.css(".auth-card")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("123123123")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.css(".auth-page")).click()
    await driver.close()
  })
})
