// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('3.producto fallido', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('3.producto fallido', async function() {
    await driver.get("https://vayo-solutions.netlify.app/")
    await driver.findElement(By.linkText("Ingresar")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("admin@vayo.cl")
    await driver.findElement(By.css(".form-group:nth-child(2)")).click()
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("Admin2026!")
    await driver.findElement(By.css(".btn")).click()
    {
      const element = await driver.findElement(By.css(".btn"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.manage().window().setRect(1050, 720)
    await driver.findElement(By.linkText("Productos")).click()
    await driver.findElement(By.css(".btn--primary")).click()
    {
      const element = await driver.findElement(By.css(".btn--primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.id("pr-cat")).click()
    await driver.findElement(By.css(".vm-dialog > div:nth-child(3)")).click()
    await driver.findElement(By.id("pr-name")).click()
    await driver.findElement(By.id("pr-name")).sendKeys("0000")
    await driver.findElement(By.css(".form-grid:nth-child(3) > .form-field:nth-child(2) > .form-label")).click()
    await driver.findElement(By.id("pr-sku")).click()
    await driver.findElement(By.id("pr-sku")).sendKeys("0000")
    await driver.findElement(By.id("pr-brand")).click()
    await driver.findElement(By.id("pr-brand")).sendKeys("000000")
    await driver.findElement(By.id("pr-model")).click()
    await driver.findElement(By.id("pr-model")).sendKeys("00000")
    await driver.findElement(By.id("pr-price")).click()
    await driver.findElement(By.id("pr-avail")).click()
    {
      const dropdown = await driver.findElement(By.id("pr-avail"))
      await dropdown.findElement(By.xpath("//option[. = 'Sin stock']")).click()
    }
    await driver.findElement(By.id("pr-desc")).click()
    await driver.findElement(By.id("pr-desc")).sendKeys("<zsxdas<")
    await driver.findElement(By.css(".btn--sm:nth-child(2)")).click()
    await driver.findElement(By.id("pr-name")).sendKeys("00000000")
  })
})
