// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('4.. Cliente fallido', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('4.. Cliente fallido', async function() {
    await driver.get("https://vayo-solutions.netlify.app/admin")
    await driver.manage().window().setRect(1050, 720)
    await driver.findElement(By.linkText("Clientes")).click()
    {
      const element = await driver.findElement(By.linkText("Ventas"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".btn--primary")).click()
    await driver.findElement(By.id("c-name")).click()
    await driver.findElement(By.id("c-name")).sendKeys("123")
    await driver.findElement(By.id("c-company")).click()
    await driver.findElement(By.id("c-company")).sendKeys("123")
    await driver.findElement(By.id("c-rut")).click()
    await driver.findElement(By.id("c-rut")).sendKeys("12-3")
    await driver.findElement(By.id("c-email")).click()
    await driver.findElement(By.id("c-email")).sendKeys("123")
    await driver.findElement(By.id("c-phone")).click()
    await driver.findElement(By.id("c-phone")).sendKeys("123")
    await driver.findElement(By.id("c-address")).click()
    await driver.findElement(By.id("c-address")).sendKeys("123")
    await driver.findElement(By.id("c-notes")).click()
    await driver.findElement(By.id("c-notes")).sendKeys("123")
    await driver.findElement(By.css("div:nth-child(3) > .btn--primary")).click()
    await driver.findElement(By.id("c-name")).click()
    await driver.findElement(By.id("c-name")).sendKeys("12334")
    await driver.findElement(By.id("c-rut")).click()
    await driver.findElement(By.id("c-rut")).sendKeys("12.334.234-4")
    await driver.findElement(By.css("div:nth-child(3) > .btn--primary")).click()
    {
      const element = await driver.findElement(By.css("div:nth-child(3) > .btn--primary"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
