// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('5.Usuario fallido', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('5.Usuario fallido', async function() {
    await driver.get("https://vayo-solutions.netlify.app/admin")
    await driver.manage().window().setRect(1050, 796)
    await driver.findElement(By.linkText("Usuarios")).click()
    {
      const element = await driver.findElement(By.linkText("Usuarios"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".btn--primary")).click()
    await driver.findElement(By.id("usr-name")).click()
    await driver.findElement(By.id("usr-name")).sendKeys("12334123")
    await driver.findElement(By.id("usr-email")).click()
    await driver.findElement(By.id("usr-email")).sendKeys("12345qwe@das")
    await driver.findElement(By.id("usr-pass")).click()
    await driver.findElement(By.id("usr-pass")).sendKeys("1234")
    await driver.findElement(By.id("usr-pos")).click()
    await driver.findElement(By.id("usr-pos")).sendKeys("qwe")
    await driver.findElement(By.id("usr-phone")).click()
    await driver.findElement(By.id("usr-phone")).sendKeys("qwe")
    await driver.findElement(By.css(".btn--sm:nth-child(2)")).click()
    await driver.findElement(By.id("usr-name")).click()
    await driver.findElement(By.id("usr-name")).sendKeys("Paula")
    await driver.findElement(By.id("usr-email")).click()
    await driver.findElement(By.id("usr-email")).sendKeys("12314")
    await driver.findElement(By.css(".vm-dialog > div:nth-child(3)")).click()
    await driver.findElement(By.css(".btn--sm:nth-child(2)")).click()
    await driver.findElement(By.id("usr-email")).click()
    await driver.findElement(By.id("usr-email")).sendKeys("12!\"#$!23|")
    await driver.findElement(By.css(".btn--sm:nth-child(2)")).click()
    await driver.findElement(By.css(".vm-head__close > svg")).click()
  })
})
