// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('7.Cotizar a un cliente(incompleta)', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('7.Cotizar a un cliente(incompleta)', async function() {
    await driver.get("https://vayo-solutions.netlify.app/")
    await driver.manage().window().setRect(1360, 658)
    await driver.findElement(By.linkText("Ingresar")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("valetes@demo.cl")
    await driver.findElement(By.id("password")).click()
    await driver.findElement(By.id("password")).sendKeys("ConTraseña")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.linkText("Clientes")).click()
    await driver.findElement(By.css("tr:nth-child(40) > .td--actions > .btn--ghost")).click()
    await driver.findElement(By.css(".form-group--street > .input")).click()
    await driver.findElement(By.css(".ng-dirty:nth-child(2)")).sendKeys("Test")
    await driver.findElement(By.css(".form-group:nth-child(1) > .ng-invalid")).click()
    await driver.findElement(By.css(".form-row--3 > .form-group:nth-child(1) > .ng-untouched")).sendKeys("Viña del Mar")
    await driver.findElement(By.css(".form-group:nth-child(3) > .ng-dirty")).sendKeys("2520000")
    await driver.findElement(By.css(".form-group:nth-child(4) > .input")).click()
    await driver.findElement(By.css(".form-group:nth-child(4) > .input")).sendKeys("edificio con letrero grande")
    await driver.findElement(By.css(".textarea")).click()
    await driver.findElement(By.css(".textarea")).sendKeys("test")
    await driver.findElement(By.css(".checkbox--terms > .ng-untouched")).click()
    await driver.findElement(By.css(".checkbox:nth-child(3)")).click()
  })
})
